// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZGlTuwYv8nKj4rveWjXJtfwNJQ4CBWQ',
    appId: '1:339266720439:android:a67891eaeb9bdea16a7332',
    messagingSenderId: '339266720439',
    projectId: 'ldfews',
    storageBucket: 'ldfews.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMCdndADxaL89fvEPN6Z5m9m5zQ_IRw54',
    appId: '1:339266720439:ios:935b3e2f2fd1ac386a7332',
    messagingSenderId: '339266720439',
    projectId: 'ldfews',
    storageBucket: 'ldfews.firebasestorage.app',
    iosBundleId: 'com.example.ldfews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOZrb9Ds0wqxZKvqBIwPRrZI5zTtPLdLU',
    appId: '1:339266720439:web:90b8377fcf661ce86a7332',
    messagingSenderId: '339266720439',
    projectId: 'ldfews',
    authDomain: 'ldfews.firebaseapp.com',
    storageBucket: 'ldfews.firebasestorage.app',
    measurementId: 'G-QC6KK79MBS',
  );
}
